In [3]:
!pip install pandas
!pip install numpy
!pip install -U scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [9]:
import numpy as np
import pandas

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [27]:

# load the dataset
dataframe = pandas.read_csv('/content/drive/MyDrive/prosaindata/tugas/airline-passengers.csv',  usecols=[1], engine='python')
data = dataframe.values
data = data.astype('int')

# Membuat sample input dan output
look_back = 2
input_data, output_data = [], []
for i in range(len(data)-look_back-1):
    a = data[i:(i+look_back), 0]
    input_data.append(a)
    output_data.append(data[i + look_back, 0])

input_data = np.array(input_data)
output_data = np.array(output_data)

# Menampilkan sample input dan output
print("Sample input:")
print(input_data[:20])
print("\nSample output:")
print(output_data[:20])

df = pandas.DataFrame({'xt-2': input_data[:,0], 'xt-1': input_data[:,1], 'xt': output_data})
print(df)
df.to_csv('airlines_data.csv', index=False, columns=['xt-2', 'xt-1', 'xt'])


Sample input:
[[112 118]
 [118 132]
 [132 129]
 [129 121]
 [121 135]
 [135 148]
 [148 148]
 [148 136]
 [136 119]
 [119 104]
 [104 118]
 [118 115]
 [115 126]
 [126 141]
 [141 135]
 [135 125]
 [125 149]
 [149 170]
 [170 170]
 [170 158]]

Sample output:
[132 129 121 135 148 148 136 119 104 118 115 126 141 135 125 149 170 170
 158 133]
     xt-2  xt-1   xt
0     112   118  132
1     118   132  129
2     132   129  121
3     129   121  135
4     121   135  148
..    ...   ...  ...
136   472   535  622
137   535   622  606
138   622   606  508
139   606   508  461
140   508   461  390

[141 rows x 3 columns]


In [36]:
import numpy as np

def split_sequence(sequence, n_steps, n_features):
    X, y = [], []
    for i in range(len(sequence)):
        # Mencari index akhir dari sequence yang ingin dipisahkan
        end_ix = i + n_steps
        # Memastikan index akhir tidak melebihi panjang sequence
        if end_ix > len(sequence)-1:
            break
        # Mendapatkan input dan output untuk sequence saat ini
        seq_x, seq_y = sequence[i:end_ix, :-1], sequence[end_ix, -1]
        X.append(seq_x)
        y.append(seq_y)
    # Mengubah list menjadi array numpy
    X = np.array(X)
    y = np.array(y)
    return X, y

# Membaca dataset
dataset = np.loadtxt("/content/drive/MyDrive/prosaindata/tugas/airline-passengers.csv", delimiter=",", usecols=1, skiprows=1)

# Menambahkan kolom kedua ke dataset
dataset = np.column_stack((dataset, dataset))

# Menentukan jumlah time steps
n_steps = 2

# Memisahkan dataset menjadi input dan output menggunakan fungsi split_sequence
X, y = split_sequence(dataset, n_steps, n_features=2)

# Menampilkan sample input dan output
for i in range(len(X)):
  print(X[i], y[i])

df = pandas.DataFrame({'xt-2': X[:,0], 'xt-1': X[:,1], 'xt': y[]})
print(df)


[[112.]
 [118.]] 132.0
[[118.]
 [132.]] 129.0
[[132.]
 [129.]] 121.0
[[129.]
 [121.]] 135.0
[[121.]
 [135.]] 148.0
[[135.]
 [148.]] 148.0
[[148.]
 [148.]] 136.0
[[148.]
 [136.]] 119.0
[[136.]
 [119.]] 104.0
[[119.]
 [104.]] 118.0
[[104.]
 [118.]] 115.0
[[118.]
 [115.]] 126.0
[[115.]
 [126.]] 141.0
[[126.]
 [141.]] 135.0
[[141.]
 [135.]] 125.0
[[135.]
 [125.]] 149.0
[[125.]
 [149.]] 170.0
[[149.]
 [170.]] 170.0
[[170.]
 [170.]] 158.0
[[170.]
 [158.]] 133.0
[[158.]
 [133.]] 114.0
[[133.]
 [114.]] 140.0
[[114.]
 [140.]] 145.0
[[140.]
 [145.]] 150.0
[[145.]
 [150.]] 178.0
[[150.]
 [178.]] 163.0
[[178.]
 [163.]] 172.0
[[163.]
 [172.]] 178.0
[[172.]
 [178.]] 199.0
[[178.]
 [199.]] 199.0
[[199.]
 [199.]] 184.0
[[199.]
 [184.]] 162.0
[[184.]
 [162.]] 146.0
[[162.]
 [146.]] 166.0
[[146.]
 [166.]] 171.0
[[166.]
 [171.]] 180.0
[[171.]
 [180.]] 193.0
[[180.]
 [193.]] 181.0
[[193.]
 [181.]] 183.0
[[181.]
 [183.]] 218.0
[[183.]
 [218.]] 230.0
[[218.]
 [230.]] 242.0
[[230.]
 [242.]] 209.0
[[242.]
 [2

ValueError: ignored